import { Slip, SlipLineItem, ActivityLogEntry } from "@/types/slips";

const mockLineItems: SlipLineItem[] = [
  {
    id: "li-001",
    slip_id: "slip-001",
    description: "Full Cream Milk 2L",
    quantity: 2,
    unit_price: 32.99,
    total_price: 65.98,
    is_corrected: false,
    corrected_description: null,
    corrected_quantity: null,
    corrected_unit_price: null,
    corrected_total_price: null,
    brand_campaign_match: "Clover",
  },
  {
    id: "li-002",
    slip_id: "slip-001",
    description: "White Bread 700g",
    quantity: 1,
    unit_price: 16.99,
    total_price: 16.99,
    is_corrected: false,
    corrected_description: null,
    corrected_quantity: null,
    corrected_unit_price: null,
    corrected_total_price: null,
    brand_campaign_match: null,
  },
  {
    id: "li-003",
    slip_id: "slip-001",
    description: "Free Range Eggs 6pk",
    quantity: 1,
    unit_price: 42.99,
    total_price: 42.99,
    is_corrected: false,
    corrected_description: null,
    corrected_quantity: null,
    corrected_unit_price: null,
    corrected_total_price: null,
    brand_campaign_match: null,
  },
  {
    id: "li-004",
    slip_id: "slip-001",
    description: "Cheddar Cheese 400g",
    quantity: 1,
    unit_price: 69.99,
    total_price: 69.99,
    is_corrected: false,
    corrected_description: null,
    corrected_quantity: null,
    corrected_unit_price: null,
    corrected_total_price: null,
    brand_campaign_match: null,
  },
  {
    id: "li-005",
    slip_id: "slip-001",
    description: "Bananas per kg",
    quantity: 1,
    unit_price: 18.5,
    total_price: 18.5,
    is_corrected: false,
    corrected_description: null,
    corrected_quantity: null,
    corrected_unit_price: null,
    corrected_total_price: null,
    brand_campaign_match: null,
  },
];

const mockActivity: ActivityLogEntry[] = [
  {
    id: "act-001",
    slip_id: "slip-001",
    moderator_id: null,
    action: "noted",
    details: "AI processed slip with 92% confidence. Recommended: AUTO_APPROVE",
    created_at: "2026-02-13T08:30:00Z",
    moderator: { name: "AI System", email: "ai@system" },
  },
  {
    id: "act-002",
    slip_id: "slip-001",
    moderator_id: "mod-001",
    action: "noted",
    details: "Flagged for manual review due to high transaction amount",
    created_at: "2026-02-13T09:15:00Z",
    moderator: { name: "Sarah Johnson", email: "sarah@savvysaver.co.za" },
  },
];

export const mockSlips: Slip[] = [
  {
    id: "slip-001",
    created_at: "2026-02-13T08:25:00Z",
    image_url: "/mock-slip-1.jpg",
    user_id: "user-abc-123",
    status: "manual_review",
    ai_processed_at: "2026-02-13T08:30:00Z",
    ai_processing_time_ms: 2340,
    ai_model_used: "claude-opus-4-6",
    ai_cost_usd: 0.0045,
    recommended_action: "MANUAL_REVIEW",
    reviewed_by: null,
    reviewed_at: null,
    review_notes: null,
    retailer_name: "Pick n Pay",
    store_branch: "Sandton City",
    slip_date: "2026-02-12",
    slip_time: "14:32:00",
    total_amount: 214.45,
    vat_amount: 27.97,
    payment_method: "Card",
    till_number: "07",
    receipt_number: "PNP-2026-00847293",
    barcode_data: "2026021207084729",
    line_items_count: 5,
    ai_response: { model: "claude-opus-4-6", version: "1.0" },
    extraction_confidence: 0.92,
    approved_retailer: true,
    slip_within_7_days: true,
    is_valid: true,
    fraud_risk_score: 0.15,
    fraud_risk_level: "LOW",
    is_direct_photo: true,
    fraud_flags: [],
    corrected_data: null,
    was_corrected: false,
    image_hash: "abc123def456",
    is_duplicate: false,
    duplicate_of: null,
    line_items: mockLineItems,
    activity_log: mockActivity,
  },
  {
    id: "slip-002",
    created_at: "2026-02-13T07:10:00Z",
    image_url: "/mock-slip-2.jpg",
    user_id: "user-def-456",
    status: "manual_review",
    ai_processed_at: "2026-02-13T07:15:00Z",
    ai_processing_time_ms: 3100,
    ai_model_used: "claude-opus-4-6",
    ai_cost_usd: 0.0052,
    recommended_action: "AUTO_REJECT",
    reviewed_by: null,
    reviewed_at: null,
    review_notes: null,
    retailer_name: "Checkers",
    store_branch: "Rosebank Mall",
    slip_date: "2026-01-28",
    slip_time: "09:15:00",
    total_amount: 567.3,
    vat_amount: 74.0,
    payment_method: "Cash",
    till_number: "03",
    receipt_number: "CHK-2026-00193847",
    barcode_data: "2026012803019384",
    line_items_count: 12,
    ai_response: null,
    extraction_confidence: 0.78,
    approved_retailer: true,
    slip_within_7_days: false,
    is_valid: false,
    fraud_risk_score: 0.45,
    fraud_risk_level: "MEDIUM",
    is_direct_photo: false,
    fraud_flags: ["screenshot_detected", "low_resolution", "metadata_mismatch"],
    corrected_data: null,
    was_corrected: false,
    image_hash: "xyz789ghi012",
    is_duplicate: false,
    duplicate_of: null,
    line_items: [
      {
        id: "li-010",
        slip_id: "slip-002",
        description: "Coca-Cola 2L",
        quantity: 3,
        unit_price: 22.99,
        total_price: 68.97,
        is_corrected: false,
        corrected_description: null,
        corrected_quantity: null,
        corrected_unit_price: null,
        corrected_total_price: null,
        brand_campaign_match: "Coca-Cola",
      },
      {
        id: "li-011",
        slip_id: "slip-002",
        description: "Simba Chips 125g",
        quantity: 5,
        unit_price: 14.99,
        total_price: 74.95,
        is_corrected: false,
        corrected_description: null,
        corrected_quantity: null,
        corrected_unit_price: null,
        corrected_total_price: null,
        brand_campaign_match: null,
      },
    ],
    activity_log: [
      {
        id: "act-010",
        slip_id: "slip-002",
        moderator_id: null,
        action: "noted",
        details:
          "AI processed slip with 78% confidence. Recommended: AUTO_REJECT. Flags: screenshot detected, low resolution",
        created_at: "2026-02-13T07:15:00Z",
        moderator: { name: "AI System", email: "ai@system" },
      },
    ],
  },
  {
    id: "slip-003",
    created_at: "2026-02-12T16:45:00Z",
    image_url: "/mock-slip-3.jpg",
    user_id: "user-ghi-789",
    status: "auto_approved",
    ai_processed_at: "2026-02-12T16:47:00Z",
    ai_processing_time_ms: 1800,
    ai_model_used: "claude-opus-4-6",
    ai_cost_usd: 0.0038,
    recommended_action: "AUTO_APPROVE",
    reviewed_by: null,
    reviewed_at: null,
    review_notes: null,
    retailer_name: "Woolworths",
    store_branch: "V&A Waterfront",
    slip_date: "2026-02-12",
    slip_time: "16:20:00",
    total_amount: 89.97,
    vat_amount: 11.74,
    payment_method: "Card",
    till_number: "12",
    receipt_number: "WW-2026-00562134",
    barcode_data: "2026021212056213",
    line_items_count: 3,
    ai_response: null,
    extraction_confidence: 0.97,
    approved_retailer: true,
    slip_within_7_days: true,
    is_valid: true,
    fraud_risk_score: 0.05,
    fraud_risk_level: "LOW",
    is_direct_photo: true,
    fraud_flags: [],
    corrected_data: null,
    was_corrected: false,
    image_hash: "mno345pqr678",
    is_duplicate: false,
    duplicate_of: null,
    line_items: [
      {
        id: "li-020",
        slip_id: "slip-003",
        description: "Rotisserie Chicken",
        quantity: 1,
        unit_price: 89.97,
        total_price: 89.97,
        is_corrected: false,
        corrected_description: null,
        corrected_quantity: null,
        corrected_unit_price: null,
        corrected_total_price: null,
        brand_campaign_match: null,
      },
    ],
    activity_log: [
      {
        id: "act-020",
        slip_id: "slip-003",
        moderator_id: null,
        action: "approved",
        details: "AI auto-approved with 97% confidence",
        created_at: "2026-02-12T16:47:00Z",
        moderator: { name: "AI System", email: "ai@system" },
      },
    ],
  },
  {
    id: "slip-004",
    created_at: "2026-02-12T12:00:00Z",
    image_url: "/mock-slip-4.jpg",
    user_id: "user-jkl-012",
    status: "approved",
    ai_processed_at: "2026-02-12T12:02:00Z",
    ai_processing_time_ms: 2100,
    ai_model_used: "claude-opus-4-6",
    ai_cost_usd: 0.0041,
    recommended_action: "MANUAL_REVIEW",
    reviewed_by: "Sarah Johnson",
    reviewed_at: "2026-02-12T14:30:00Z",
    review_notes: "Verified. Amount matches items.",
    retailer_name: "Spar",
    store_branch: "Greenstone Mall",
    slip_date: "2026-02-11",
    slip_time: "11:45:00",
    total_amount: 345.6,
    vat_amount: 45.08,
    payment_method: "Card",
    till_number: "05",
    receipt_number: "SPAR-2026-00483920",
    barcode_data: "2026021105048392",
    line_items_count: 8,
    ai_response: null,
    extraction_confidence: 0.85,
    approved_retailer: true,
    slip_within_7_days: true,
    is_valid: true,
    fraud_risk_score: 0.22,
    fraud_risk_level: "LOW",
    is_direct_photo: true,
    fraud_flags: ["slight_blur"],
    corrected_data: null,
    was_corrected: false,
    image_hash: "stu901vwx234",
    is_duplicate: false,
    duplicate_of: null,
    line_items: [],
    activity_log: [
      {
        id: "act-030",
        slip_id: "slip-004",
        moderator_id: null,
        action: "noted",
        details: "AI processed slip with 85% confidence. Recommended: MANUAL_REVIEW. Flag: slight blur detected",
        created_at: "2026-02-12T12:02:00Z",
        moderator: { name: "AI System", email: "ai@system" },
      },
      {
        id: "act-031",
        slip_id: "slip-004",
        moderator_id: "mod-001",
        action: "approved",
        details: "Verified. Amount matches items.",
        created_at: "2026-02-12T14:30:00Z",
        moderator: { name: "Sarah Johnson", email: "sarah@savvysaver.co.za" },
      },
    ],
  },
  {
    id: "slip-005",
    created_at: "2026-02-11T19:30:00Z",
    image_url: "/mock-slip-5.jpg",
    user_id: "user-mno-345",
    status: "rejected",
    ai_processed_at: "2026-02-11T19:32:00Z",
    ai_processing_time_ms: 2900,
    ai_model_used: "claude-opus-4-6",
    ai_cost_usd: 0.005,
    recommended_action: "AUTO_REJECT",
    reviewed_by: "James Mokoena",
    reviewed_at: "2026-02-12T08:00:00Z",
    review_notes: "Confirmed duplicate submission. Same receipt uploaded by another user.",
    retailer_name: "Shoprite",
    store_branch: "Menlyn Park",
    slip_date: "2026-02-10",
    slip_time: "18:05:00",
    total_amount: 156.8,
    vat_amount: 20.46,
    payment_method: "Cash",
    till_number: "09",
    receipt_number: "SR-2026-00729384",
    barcode_data: "2026021009072938",
    line_items_count: 4,
    ai_response: null,
    extraction_confidence: 0.88,
    approved_retailer: true,
    slip_within_7_days: true,
    is_valid: false,
    fraud_risk_score: 0.72,
    fraud_risk_level: "HIGH",
    is_direct_photo: false,
    fraud_flags: ["duplicate_receipt", "different_user", "metadata_stripped"],
    corrected_data: null,
    was_corrected: false,
    image_hash: "yza567bcd890",
    is_duplicate: true,
    duplicate_of: "slip-003",
    line_items: [],
    activity_log: [
      {
        id: "act-040",
        slip_id: "slip-005",
        moderator_id: null,
        action: "noted",
        details:
          "AI processed slip with 88% confidence. Recommended: AUTO_REJECT. Flags: duplicate receipt, different user, metadata stripped",
        created_at: "2026-02-11T19:32:00Z",
        moderator: { name: "AI System", email: "ai@system" },
      },
      {
        id: "act-041",
        slip_id: "slip-005",
        moderator_id: "mod-002",
        action: "rejected",
        details: "Confirmed duplicate submission. Same receipt uploaded by another user.",
        created_at: "2026-02-12T08:00:00Z",
        moderator: { name: "James Mokoena", email: "james@savvysaver.co.za" },
      },
    ],
  },
];
